<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/11 17:38:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=asandbox;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'attributes' => 
  array (
    'DEFAULT_TABLE_TYPE' => 'INNODB',
    'DEFAULT_TABLE_CHARSET' => 'utf8',
    'DEFAULT_TABLE_COLLATE' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
