<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/11/11 17:38:30
sfConfig::add(array(
  'mod_aslideshowslot_enabled' => true,
  'mod_aslideshowslot_view_class' => 'sfPHP',
));
