<?php
// auto-generated by sfViewConfigHandler
// date: 2013/11/12 10:14:27
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('/apostropheExtraSlotsPlugin/css/aExtraSlots.less', '', array (  'data-asset-group' => 'global',));
  $response->addStylesheet('/apostropheFeedbackPlugin/css/aFeedback.less', '', array (  'data-asset-group' => 'global',));
  $response->addStylesheet('/apostropheAwesomeLoginPlugin/css/aAwesomeLogin.less', '', array (  'data-asset-group' => 'global',));
  $response->addStylesheet('main.less', 'last', array (  'data-asset-group' => 'global',));
  $response->addStylesheet('/apostrophePeoplePlugin/css/aPeople.less', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostrophePlugin/js/jquery.cookie.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostropheBlogPlugin/js/aBlog.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostropheExtraSlotsPlugin/js/aExtraSlots.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostropheFeedbackPlugin/js/aFeedback.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostrophePeoplePlugin/js/aPeople.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostropheAwesomeLoginPlugin/js/jquery.tmpl.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('/apostropheAwesomeLoginPlugin/js/aAwesomeLogin.js', '', array (  'data-asset-group' => 'global',));
  $response->addJavascript('site.js', 'last', array (  'data-asset-group' => 'global',));


